{{- if .Values.backup.firstBackup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-backup-first
  labels: {{- include "sg-db.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.backup.activeDeadlineSeconds }}
  template:
    spec: {{- include "sg-db.backupPod" (dict "root" . "mode" "first") | nindent 6 }}
{{- end }}
