{{- include "sg-db.validate" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels: {{- include "sg-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
  APP_PASSWORD: {{ .Values.auth.appPassword | quote }}
