apiVersion: v2
name: application
description: A Helm chart for deploying a highly available and scalable application in Kubernetes clusters
type: application
version: 0.2.0
appVersion: "1.16.0"
maintainers: 
- name: Seagit
  email: contact@seagit.com
  url: https://seagit.com
