{{- if not .Values.existingServiceAccount }}
{{- range .Values.sources }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-src-{{ .id }}
  labels: {{- include "rag-sync.labels" $ | nindent 4 }}
  {{- with .roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
