name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.8.0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=charts::$changed"
            if echo "$changed" | grep -q "cert-manager-issuers"; then
            echo "cert-ex-changed=true" >> "$GITHUB_ENV"
            echo "::set-output name=cert-ex-changed::true"
            else
            echo "cert-ex-changed=false" >> "$GITHUB_ENV"
            echo "::set-output name=cert-ex-changed::false"
            fi
          fi
          
# echo "changed-charts=$changed" >> "$GITHUB_ENV"
# if : env.cert-extension-changed == 'true'

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: cert-manager (install)
        if: steps.list-changed.outputs.cert-ex-changed == 'true' 
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager --create-namespace \
            --set installCRDs=true \
            --wait

      - name: Run chart-testing (install)
        run: ct install
# https://github.com/marketplace/actions/helm-chart-testing